image1: edla4326/springboot_java8
image2: edla4326/springboot_java10
image3: edla4326/springbootjetty_java8
image4: edla4326/springbootjetty_java10
image5: edla4326/springbootlibsimple_java8
image6: edla4326/springbootlibsimple_java10
image7: edla4326/springbootlibjetty_java8
image8: edla4326/springbootlibjetty_java10
image9: edla4326/springbootundertow_java10
image10: elda4326/gitspringbootundertow_java8